{
  "openapi": "3.0.3",
  "info": {
    "title": "API para Aplicação de Marketplace (Projeto Marketplace)",
    "description": "Essa API tem como objetivo gerenciar todo o fluxo da aplicação: Gerencimento de Admin, Colaboradores, Donos de Loja e Clientes.",
    "contact": {
      "name": "Alex Sandro Belfort Corrêa",
      "email": "alex.sandro_as@hotmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://",
      "description": "API de Producação"
    },
    {
      "url": "http://localhost:5000/",
      "description": "API de Testes"
    }
  ],
  "paths": {
    "/": {
      "get": {
        "summary": "Rota de Status da API",
        "description": "Rota checar o status da API.",
        "tags": ["service"],

        "responses": {
          "404": {
            "description": "Not Found"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Responses-SingleMessage"
                }
              }
            }
          }
        }
      }
    },
    "/admin/create": {
      "post": {
        "summary": "Novo Usuário Admin",
        "description": "Rota para cadastro de usuário nível Admin.",
        "tags": ["admin"],
        "requestBody": {
          "required": true,
          "content": {
            "aplication/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Create-Admin"
              },
              "examples": {
                "Novo Usuário": {
                  "value": {
                    "firstname": "Alex",
                    "lastname": "Santos",
                    "cpf": "111.222.333-44",
                    "phone": "(98) 9 7777-5555",
                    "email": "alex.santos@gmail.com",
                    "password": "12345678",
                    "confirmPassword": "12345678"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "201": {
            "description": "Created",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Response-CreateAdmin-LoginAdmin"
                }
              }
            }
          }
        }
      }
    },
    "/admin/login": {
      "post": {
        "summary": "Login de Usuário Admin",
        "description": "Rota para login de usuário nível Admin.",
        "tags": ["admin"],
        "requestBody": {
          "required": true,
          "content": {
            "aplication/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Login-Admin"
              },
              "examples": {
                "Login do Usuário": {
                  "value": {
                    "email": "alex.santos@gmail.com",
                    "password": "12345678"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Response-CreateAdmin-LoginAdmin"
                }
              }
            }
          }
        }
      }
    },
    "/admin/profile": {
      "get": {
        "summary": "Obter Perfil de Usuário Admin",
        "description": "Rota para obter informações do usuário nível Admin.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "required": false
        },
        "responses": {
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Get-Profile-Admin"
                }
              }
            }
          }
        }
      }
    },
    "/admin/updateprofile": {
      "patch": {
        "summary": "Atualizar Perfil de Usuário Admin",
        "description": "Rota para atualizar cadastro de usuário nível Admin.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "aplication/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Update-Profile-Admin"
              },
              "examples": {
                "Atualizar Usuário": {
                  "value": {
                    "firstname": "Alex",
                    "lastname": "Santos",
                    "cpf": "111.222.333-44",
                    "phone": "(98) 9 7777-5555",
                    "email": "alex.santos@gmail.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "201": {
            "description": "Created",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Responses-SingleMessage"
                }
              }
            }
          }
        }
      }
    },
    "/admin/changepassword": {
      "patch": {
        "summary": "Alterar Senha de Usuário Admin",
        "description": "Rota para alterar a senha de usuário nível Admin.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "aplication/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Update-Password-Admin"
              },
              "examples": {
                "Login do Usuário": {
                  "value": {
                    "currentPassword": "12345678",
                    "newPassword": "20232024",
                    "confirmPassword": "20232024"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Responses-SingleMessage"
                }
              }
            }
          }
        }
      }
    },
    "/admin/removeaccount": {
      "delete": {
        "summary": "Excluir Conta de Usuário Admin",
        "description": "Rota para excluir conta do usuário nível Admin.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "required": false
        },
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Responses-SingleMessage"
                }
              }
            }
          }
        }
      }
    },
    "/admin/newpermission": {
      "post": {
        "summary": "Nova Permissão",
        "description": "Rota para usuário nível Admin criar nova permissão. As permissões são aplicadas aos Colaboradores.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "aplication/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Create-Permission"
              },
              "examples": {
                "Nova Permissão": {
                  "value": {
                    "name": "CREATE_TYPE",
                    "description": "Criar Tipo de Loja"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Responses-SingleMessage"
                }
              }
            }
          }
        }
      }
    },
    "/admin/permission/{id}": {
      "get": {
        "summary": "Obter Permissão por ID",
        "description": "Rota para usuário nível Admin obter dados de permissão por ID.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID da Permissão",
            "required": true
          }
        ],
        "requestBody": {
          "required": false
        },
        "responses": {
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Get-Permission"
                }
              }
            }
          }
        }
      }
    },
    "/admin/updatepermission/{id}": {
      "patch": {
        "summary": "Atualizar Permissão por ID",
        "description": "Rota para usuário nível Admin atualizar dados de permissão por ID.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID da Permissão",
            "required": true
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "aplication/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Update-Permission"
              },
              "examples": {
                "Atualizar Permissão": {
                  "value": {
                    "name": "CREATE_NEW_STORE",
                    "description": "Criar Loja Nova"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Responses-SingleMessage"
                }
              }
            }
          }
        }
      }
    },
    "/admin/deletepermission/{id}": {
      "delete": {
        "summary": "Excluir Permissão por ID",
        "description": "Rota para usuário nível Admin excluir permissão por ID.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID da Permissão",
            "required": true
          }
        ],
        "requestBody": {
          "required": false
        },
        "responses": {
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Responses-SingleMessage"
                }
              }
            }
          }
        }
      }
    },
    "/admin/allpermissions": {
      "get": {
        "summary": "Obter Todas as Permissões",
        "description": "Rota para usuário nível Admin listar todas as Permissões disponíveis no Sistema.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [],
        "requestBody": {
          "required": false
        },
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Get-All-Permission"
                }
              }
            }
          }
        }
      }
    },
    "/admin/mypermissions": {
      "get": {
        "summary": "Obter as Permissões do Admin Logado",
        "description": "Rota para usuário nível Admin listar as permissões criadas por ele no Sistema.",
        "tags": ["admin"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [],
        "requestBody": {
          "required": false
        },
        "responses": {
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Get-My-Permission"
                }
              }
            }
          }
        }
      }
    },

    "/users/edit/{id}": {
      "patch": {
        "summary": "Atualizar Perfil do Usuário",
        "description": "Rota para salvar alterações no perfil do usuário",
        "tags": ["users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do Usuário",
            "required": true
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "aplication/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/ProfileUser"
              },
              "examples": {
                "Alterar Usuário": {
                  "value": {
                    "firstname": "Alex",
                    "lastname": "Corrêa",
                    "email": "alex.sandro_as@hotmail.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Response-Update-Profile"
                }
              }
            }
          }
        }
      }
    },
    "/users/changepassword/{id}": {
      "patch": {
        "summary": "Alterar Senha do Usuário",
        "description": "Rota para alterar a Senha do usuário",
        "tags": ["users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do Usuário",
            "required": true
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "aplication/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/PasswordUser"
              },
              "examples": {
                "Alterar Senha": {
                  "value": {
                    "currentPassword": "1234@Ae5678",
                    "newPassword": "8765@Ae4321",
                    "confirmPassword": "8765@Ae4321"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Responses-User-ChangePassword"
                }
              }
            }
          }
        }
      }
    },
    "/users/changephoto/{id}": {
      "patch": {
        "summary": "Atualizar Foto de Perfil do Usuário",
        "description": "Rota para alterar a Foto no Perfil do Usuário",
        "tags": ["users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do Usuário",
            "required": true
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "image/png": {
              "schema": {
                "type": "string",
                "format": "binary"
              },
              "examples": {
                "Alterar Usuário": {
                  "value": {
                    "firstname": "Alex",
                    "lastname": "Corrêa",
                    "email": "alex.sandro_as@hotmail.com",
                    "password": "teste@1234",
                    "confirmPassword": "teste@1234"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "Unauthorized"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "200": {
            "description": "OK",
            "content": {
              "aplication/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Response-Change-Photo"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Responses-SingleMessage": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        }
      },
      "Create-Admin": {
        "type": "object",
        "properties": {
          "firstname": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "boolean"
          },
          "confirmPassword": {
            "type": "boolean"
          }
        }
      },
      "Login-Admin": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Response-CreateAdmin-LoginAdmin": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "firstname": {
            "type": "integer"
          },
          "lastname": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "token": {
            "type": "string"
          }
        }
      },
      "Get-Profile-Admin": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "firstname": {
                "type": "string"
              },
              "lastname": {
                "type": "string"
              },
              "cpf": {
                "type": "string"
              },
              "phone": {
                "type": "string"
              },
              "email": {
                "type": "boolean"
              },
              "createdAt": {
                "type": "boolean"
              },
              "updatedAt": {
                "type": "boolean"
              }
            }
          }
        }
      },
      "Update-Profile-Admin": {
        "type": "object",
        "properties": {
          "firstname": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        }
      },
      "Update-Password-Admin": {
        "type": "object",
        "properties": {
          "currentPassword": {
            "type": "string"
          },
          "newPassword": {
            "type": "string"
          },
          "confirmPassword": {
            "type": "string"
          }
        }
      },
      "Create-Permission": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      },
      "Get-Permission": {
        "type": "object",
        "properties": {
          "permission": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "id_admin": {
                "type": "integer"
              },
              "createdAt": {
                "type": "string"
              },
              "updatedAt": {
                "type": "string"
              }
            }
          }
        }
      },
      "Update-Permission": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      },
      "Get-All-Permission": {
        "type": "object",
        "properties": {
          "allpermissions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "id_admin": {
                  "type": "integer"
                },
                "description": {
                  "type": "string"
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "Get-My-Permission": {
        "type": "object",
        "properties": {
          "mypermissions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "id_admin": {
                  "type": "integer"
                },
                "description": {
                  "type": "string"
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "Create-Colaborator": {
        "type": "object",
        "properties": {
          "firstname": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "rg": {
            "type": "string"
          },
          "org_emitter": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "email": {
            "type": "boolean"
          },
          "password": {
            "type": "boolean"
          }
        }
      },
      "Get-Colaborator": {
        "type": "object",
        "properties": {
          "colaborator": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "firstname": {
                "type": "string"
              },
              "lastname": {
                "type": "string"
              },
              "cpf": {
                "type": "string"
              },
              "rg": {
                "type": "string"
              },
              "org_emitter": {
                "type": "string"
              },
              "phone": {
                "type": "string"
              },
              "email": {
                "type": "boolean"
              },
              "id_admin": {
                "type": "boolean"
              },
              "createdAt": {
                "type": "boolean"
              },
              "updatedAt": {
                "type": "boolean"
              }
            }
          }
        }
      },
      "Update-Colaborator": {
        "type": "object",
        "properties": {
          "firstname": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "rg": {
            "type": "string"
          },
          "org_emitter": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "email": {
            "type": "boolean"
          }
        }
      },
      "Update-Password-Colaborator": {
        "type": "object",
        "properties": {
          "currentPassword": {
            "type": "string"
          },
          "newPassword": {
            "type": "string"
          },
          "confirmPassword": {
            "type": "string"
          }
        }
      },
      "Add-Permission-Colaborator": {
        "type": "object",
        "properties": {
          "id_colaborator": {
            "type": "integer"
          },
          "id_permission": {
            "type": "integer"
          }
        }
      },
      "Remove-Permission-Colaborator": {
        "type": "object",
        "properties": {
          "id_colaborator": {
            "type": "integer"
          },
          "id_permission": {
            "type": "integer"
          }
        }
      },
      "Create-Type": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "image": {
            "type": "string"
          }
        }
      },
      "Update-Name-Type": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        }
      },
      "Update-Image-Type": {
        "type": "object",
        "properties": {
          "image": {
            "type": "string"
          }
        }
      },
      "Get-Type": {
        "type": "object",
        "properties": {
          "type": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "image": {
                "type": "string"
              },
              "id_admin": {
                "type": "string"
              },
              "createdAt": {
                "type": "string"
              },
              "updatedAt": {
                "type": "string"
              }
            }
          }
        }
      },
      "Get-All-Types": {
        "type": "object",
        "properties": {
          "alltypes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "image": {
                  "type": "string"
                },
                "id_admin": {
                  "type": "string"
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "Get-My-Types": {
        "type": "object",
        "properties": {
          "mytypes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "image": {
                  "type": "string"
                },
                "id_admin": {
                  "type": "string"
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "Create-Specialitie": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "image": {
            "type": "string"
          }
        }
      },
      "Get-Specialitie": {
        "type": "object",
        "properties": {
          "specialitie": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "image": {
                "type": "string"
              },
              "id_admin": {
                "type": "string"
              },
              "createdAt": {
                "type": "string"
              },
              "updatedAt": {
                "type": "string"
              }
            }
          }
        }
      },
      "Update-Name-Specialitie": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        }
      },
      "Update-Image-Specialitie": {
        "type": "object",
        "properties": {
          "image": {
            "type": "string"
          }
        }
      },
      "Get-My-Colaborators": {
        "type": "object",
        "properties": {
          "mycolaborators": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "firstname": {
                  "type": "string"
                },
                "lastname": {
                  "type": "string"
                },
                "cpf": {
                  "type": "string"
                },
                "rg": {
                  "type": "string"
                },
                "org_emitter": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "email": {
                  "type": "boolean"
                },
                "id_admin": {
                  "type": "boolean"
                },
                "createdAt": {
                  "type": "boolean"
                },
                "updatedAt": {
                  "type": "boolean"
                }
              }
            }
          }
        }
      },
      "Get-All-Colaborators": {
        "type": "object",
        "properties": {
          "allcolaborators": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "firstname": {
                  "type": "string"
                },
                "lastname": {
                  "type": "string"
                },
                "cpf": {
                  "type": "string"
                },
                "rg": {
                  "type": "string"
                },
                "org_emitter": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "email": {
                  "type": "boolean"
                },
                "id_admin": {
                  "type": "boolean"
                },
                "createdAt": {
                  "type": "boolean"
                },
                "updatedAt": {
                  "type": "boolean"
                }
              }
            }
          }
        }
      },
      "Create-Payment": {
        "type": "object",
        "properties": {
          "value": {
            "type": "integer"
          },
          "reference": {
            "type": "string"
          },
          "date": {
            "type": "string"
          },
          "id_store": {
            "type": "string"
          }
        }
      },
      "Get-Payment": {
        "type": "object",
        "properties": {
          "payment": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "value": {
                "type": "integer"
              },
              "reference": {
                "type": "string"
              },
              "date": {
                "type": "string"
              },
              "id_store": {
                "type": "string"
              },
              "id_admin": {
                "type": "string"
              },
              "createdAt": {
                "type": "string"
              },
              "updatedAt": {
                "type": "string"
              }
            }
          }
        }
      },
      "Update-Payment": {
        "type": "object",
        "properties": {
          "value": {
            "type": "integer"
          },
          "reference": {
            "type": "string"
          },
          "date": {
            "type": "string"
          },
          "id_store": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
